### ISSUE TITLE
How can I run this docker on a non-CUDA Intel Iris Xe GPU? 

### ISSUE THREAD

**Issue by Ease78** [lazarst96/semantic-search#2]
This is the error that I am getting right now:

Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr:

Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown

**Comment by lazarst96** [comment]
Hi,

You can't run this environment on your GPU, but you can run it on the CPU. Please note - That can cause losing some performance.

You can try with the following changes:

1. Change the following code snippet from docker-compose
```
tf-serving:
  image: tensorflow/serving:latest-gpu
```

to:

```
tf-serving:
  image: tensorflow/serving:latest
```
2. Remove the following part of docker-compose:
```
deploy:
    resources:
      reservations:
        devices:
          - driver: "nvidia"
            capabilities: [ gpu ]
```
